config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  #帳號管理
  devise_for :users


  #前台管理
    root 'posts#index'
    resources 'posts'


  #後台管理
  namespace :admin do
    root 'posts#index'
    resources 'posts'
    resources 'post_categories'
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	#圖片
	mount_uploader :image, ImageUploader 

	#標籤
	acts_as_taggable
	acts_as_taggable_on :tags
	scope :post_filter, ->(tag){ tagged_with(tag) if tag.present? }	

	#欄位條件
	validates :title, presence: 'true'

	#資料表關聯
	has_many :post_categories
	

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	#欄位驗證
	validates :name, presence: 'true'

	#資料表關聯
	belongs_to :post
	
end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end

  def as_json_methods
    [:image]
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :login_required, :required_admin!


  protected
  
  #判斷如果身分是否為管理者，如果不是就倒回前台首頁。
  def required_admin!
    redirect_to posts_path, notice: '你沒有 admin 權限' unless current_user && current_user.admin?
  end
end

app/controllers/admin/post_categories_controller.rb
class Admin::PostCategoriesController < Admin::BaseController
	def index
		@post_categories = PostCategory.all
		@post_category = PostCategory.new

		@post_category_count = Post.where(:category => @post_categories.name).count
	end

	def new
		@post_category = PostCategory.new
	end

	def create
		@post_category = PostCategory.new(post_categories_params)
		if @post_category.save
			redirect_to admin_post_categories_path
		else
			render :new
		end
	end

	def edit
		@post_category = PostCategory.find(params[:id])
	end

	def update
		@post_category = PostCategory.find(params[:id])
		if @post_category.update(post_categories_params)
			redirect_to admin_post_categories_path
		else
			render :edit
		end
	end

	private
	def post_categories_params
		params.require(:post_category).permit(:name)
	end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
	def index
		@posts = Post.post_filter(params[:tag])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to new_admin_post_path
		else
			render :new
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to edit_admin_post_path(params[:id])
		else
			render :edit
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to admin_posts_url
	end

	private
	def post_params
		params.require(:post).permit(:draft ,:category_ids, :category, :author, :title, :content, :image, :status, :tag_list, :created_at)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def login_required
    if current_user.blank?
      respond_to do |format|
        format.html {
          authenticate_user!
        }
        format.all {
          head(:unauthorized)
        }
      end
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :address,:tel,:birthday,:email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :address,:tel,:birthday, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@post_find_status = Post.where(:status => "1", :draft => "0")
	end

	def show
		@post = Post.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/common/_head.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-10 col-md-10"></div>
  <div class="col-xs-2 col-md-2">
  <% if user_signed_in? && current_user.admin? %>
  Hello!!<strong><%= current_user.name %></strong></br>
  <%= link_to '後台', admin_posts_url %> |
  <%= link_to '前台', posts_url %></br>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% elsif user_signed_in?  %>
  Hello!!<strong><%= current_user.name %></strong></br>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
	</div>
</div>


app/views/admin/common/_menu.html.erb
<div class="col-xs-12 col-sm-3 col-md-2 left-side">
	<a id="logo" href="">
		<img src="">
		logo
	</a>
	<span id="toggle-menu"><i class="icon glyphicon glyphicon-align-justify"></i>Menu</span>
	<ul class="active">
		<li>
			<%= link_to admin_posts_url do %>
				<i class="icon glyphicon glyphicon-pushpin"></i>
				<span class="xn-text">文章管理</span>
			<% end %>
			<ul class="menu-child-category">
				<li><%= link_to('所有文章', admin_posts_url, class: :"active") %></li>
				<li><%= link_to('分類管理', admin_post_categories_path) %></li>
			</ul>
		</li>
		<li><a href=""><i class="icon glyphicon glyphicon-file"></i></a></li>
		<li><a href=""><i class="icon glyphicon glyphicon-bookmark"></i></a></li>
		<li><a href=""><i class="icon glyphicon glyphicon-briefcase"></i></a></li>
		<li><a href=""><i class="icon glyphicon glyphicon-cog"></i></a></li>
	</ul>
</div>

app/views/admin/post_categories/_form.html.erb
<div class="col-xs-12 col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 article">
	<!-- 頁面標題 -->
	<div class="page-title"> 
		<h2>新增分類</h2>
	</div>
<%= bootstrap_form_for [:admin, @post_category] do |f| %>
	<%= f.text_field :name %>
	<%= f.submit '送出' %>
<% end %>
<%= link_to('返回上一頁', admin_post_categories_path) %>
</div>

app/views/admin/post_categories/index.html.erb
<%= render 'admin/common/head' %>
<div class="container-fluid post-categories">
	<div class="row">
		<%= render 'admin/common/menu' %>
	<div class="col-xs-12 col-sm-3 col-sm-offset-3 col-md-3 col-md-offset-2 article">
		<!-- 頁面標題 -->
		<div class="page-title"> 
			<h2>分類管理</h2>
		</div>
		<h4>增加新分類</h4>
		<%= bootstrap_form_for [:admin, @post_category] do |a| %>
		<div class="form-group">
			<%= a.text_field :name, class: :"form-control", placeholder: :"輸入分類名稱", label: :"分類名稱" %>
		</div>
			<%= a.submit '確認新增', class: :"btn btn-primary" %>
		<% end %>
	</div>
	<div class="col-xs-12 col-sm-6 col-sm-offset-6 col-md-7 col-md-offset-5 article">
		<div class="page-content-wrap">
			<div class="row">
				<div class="col-md-12">
					<h4>管理類別</h4>
					<!-- 關鍵字搜尋 -->
					<div class="search col-md-6">
						<input class="form-control" type="text" placeholder="搜尋">
						<a href="" class="btn btn-default">
							<span class="glyphicon glyphicon-search"></span>
						</a>
					</div>
					<!-- 條件篩選 -->
					<div class="select col-md-6">
						<select class="form-control">
                            <option>批次管理</option>
                            <option>批次管理</option>
                            <option>批次管理</option>
                      	</select>
                      	<a href="" class="btn btn-default">套用</a>
					</div>
					<!-- 表格 -->
					<table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th><input type="checkbox">全選</th>
                                <th>分類名</th>
                                <th>文章數</th>
                            </tr>
                        </thead>
                        <tbody>
                        	<% @post_categories.each do |i| %>
                            <tr>
                              <td><input type="checkbox"></td>
                              <td>
                              	<%= link_to(i.name, edit_admin_post_category_path(i), class: :"post-list-title") %>
                              	<div class="post-list-action">
                                	<span><a href="">編輯</a>　|　</span>
                                	<span><a href="">刪除</a>　|　</span>
                                	<span><a href="">查看</a></span>
                                </div>
                              </td>
                              <td><%= @post_category_count %></td>
                            </tr>
                        	<% end %>                            
                        </tbody>
                    </table>
                    <!-- 頁數 -->
					<nav>
				      <ul class="pagination">
				        <li class="disabled"><a href="#">«</a></li>
				        <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
				        <li><a href="#">2</a></li>
				        <li><a href="#">3</a></li>
				        <li><a href="#">4</a></li>
				        <li><a href="#">5</a></li>
				        <li><a href="#">»</a></li>
				     </ul>
				   </nav>

				</div><!-- col-md-12 END -->
			</div><!-- row-fluid END -->
		</div><!-- page-content-wrap END -->
	</div>
</div> <!-- row END -->
</div> <!-- container-fluid END -->

app/views/admin/post_categories/new.html.erb
<%= render 'admin/common/head' %>
<div class="container-fluid">
	<div class="row">
		<%= render 'admin/common/menu' %>
			<%= render 'form' %>		
	</div> <!-- row END -->
</div> <!-- container-fluid END -->


app/views/admin/posts/_form.html.erb
<div class="col-xs-12 col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 article">
	<!-- 頁面標題 -->
	<div class="page-title"> 
		<h2>新增文章</h2>
	</div>
	<%= bootstrap_form_for [:admin, @post] do |n| %>
	<div class="page-content-wrap">
		<div class="row">
			<div class="col-md-12">
				<!-- 左邊大區塊 -->
				<div class="col-md-8 add-post-left">
					<%= n.text_field :title, class: "form-control", placeholder: "文章名稱" %>	
					<%= n.hidden_field :author, class: "form-control", value: current_user.name %>		
					<%= n.text_area :content, :class => "redactor", :rows => 40, :cols => 120 %>
				</div>
				<!-- 右邊小區塊 -->
				<div class="col-md-4 add-post-right">
					<!-- 發布 -->
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">發佈</h3>
						</div>
						<div class="panel-body">
							<div class="btn-group">
								<%= link_to('查看', post_path(@post), class: :"btn btn-default") %>
								<%= link_to('取消', admin_posts_url, class: :"btn btn-default") %>
								<%= n.submit '發佈', class: :"btn btn-primary" %>							
							</div>							
							<div class="pub-section">
								<span class="title">狀態</span>
								<label class="radio-inline">
								<%= n.radio_button :status, "1", label: :"公開", :checked => (@post.status? == true) %>
								</label>
								<label class="radio-inline">
								<%= n.radio_button :status, "0", label: :"隱藏", :checked => (@post.status? == false)%>
								</label>				
							</div>
							<div class="pub-section">
								<span class="title">存成草稿</span>
								<label class="radio-inline">
								<%= n.radio_button :draft, "1", label: :"是", :checked => (@post.draft? == true) %>
								</label>
								<label class="radio-inline">
								<%= n.radio_button :draft, "0", label: :"否", :checked => (@post.draft? == false)%>
								</label>				
							</div>
						</div>
					</div><!-- 發布 結束-->
					<!-- 分類 -->
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">分類</h3>
						</div>
						<div class="panel-body">
							<div class="checkbox">								
								<%= n.collection_check_boxes :category, PostCategory.all, :id, :name %>
							<a type="button" class="btn btn-default pull-right">增加新類別</a>
						</div>
					</div><!-- 分類 結束-->
					<!-- 標籤 -->
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">標籤</h3>
						</div>
						<div class="panel-body">
							<div class="checkbox">
								<label>
									<%= n.text_field :tag_list, class: "form-control", placeholder: "標籤" %>
									請用逗號做區隔(例:文章,日誌,...)
								</label>
							</div>
						</div>
					</div><!-- 標籤 結束-->
					<!-- 特色圖片 -->
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">特色圖片</h3>
						</div>
						<div class="panel-body">
							<div class="form-group file">
								<input type="file" id="exampleInputFile">
							</div>
						</div>
					</div><!-- 特色圖片 結束-->
				</div><!-- 右邊小區塊 結束 -->
			</div><!-- col-md-12 END -->
		</div><!-- row-fluid END -->
	</div><!-- page-content-wrap END -->
	<% end %>
</div>



app/views/admin/posts/edit.html.erb
<%= render 'admin/common/head' %>
<div class="blog-container">
	<div class="row">
  	<div class="col-xs-2">
  		<%= render 'admin/common/menu' %>
 	 	</div>
  	<div class="col-xs-10"> 
			<%= render 'form' %>
		</div>
	</div>			
</div>

app/views/admin/posts/index.html.erb
<%= render 'admin/common/head' %>
<div class="container-fluid">
	<div class="row">
		<%= render 'admin/common/menu' %>
<div class="col-xs-12 col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 article">
		<!-- 頁面標題 -->
		<div class="page-title"> 
			<h2>文章</h2>
		</div>
		<%= link_to('新增文章', new_admin_post_path, class: :"add-article btn btn-default") %>		
		<div class="page-content-wrap">
			<div class="row">
				<div class="col-md-12">
					<!-- 關鍵字搜尋 -->
					<div class="search col-md-6">
						<input class="form-control" type="text" placeholder="搜尋">
						<a href="" class="btn btn-default">
							<span class="glyphicon glyphicon-search"></span>
						</a>
					</div>
					<!-- 條件篩選 -->
					<div class="select col-md-6">
						<select class="form-control">
                <option>批次管理</option>
                <option>批次管理</option>
                <option>批次管理</option>
          	</select>
          	<a href="" class="btn btn-default">套用</a>
						<select class="form-control">
                <option>全部日期</option>
                <option>全部日期</option>
                <option>全部日期</option>
          	</select>
          	<a href="" class="btn btn-default">篩選</a>
					</div>
					<!-- 表格 -->
					<table class="table table-bordered table-hover">
	          <thead>
	              <tr>
	                  <th><input type="checkbox">全選</th>
	                  <th>標題</th>
	                  <th>作者</th>
	                  <th>分類</th>
	                  <th>標籤</th>
	                  <th>日期</th>
	              </tr>
	          </thead>
	          <% @posts.each do |i| %>
	          <tbody>
	            <tr>
	              <td><input type="checkbox"></td>
	              <td><%= link_to i.title, edit_admin_post_path(i) %>
	                  <div class="post-list-action">
	                	<span><%= link_to('編輯', edit_admin_post_path(i)) %>  |  </span>
	                	<span><%= link_to('刪除', admin_post_path(i), method: :delete, data: {confirm: "確定要刪除此文章嗎"}) %>  |  </span>
	                	<span><%= link_to('查看', post_path(i)) %></span>
	                </div>
	              </td>
	              <td><%= i.author %></td>
	              <td><%= i.category %></td>
	              <td><%= i.tag_list %></td>
	              <td><%= i.created_at %></td>
	            </tr>
	          </tbody>
	          <% end %>
	      </table>
	      <!-- 頁數 -->
					<nav>
				      <ul class="pagination">
				        <li class="disabled"><a href="#">«</a></li>
				        <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
				        <li><a href="#">2</a></li>
				        <li><a href="#">3</a></li>
				        <li><a href="#">4</a></li>
				        <li><a href="#">5</a></li>
				        <li><a href="#">»</a></li>
				     </ul>
				   </nav>

				</div><!-- col-md-12 END -->
			</div><!-- row-fluid END -->
		</div><!-- page-content-wrap END -->		
	</div>
</div> <!-- row END -->
</div> <!-- container-fluid END -->

app/views/admin/posts/new.html.erb
<%= render 'admin/common/head' %>
<div class="container-fluid">
	<div class="row">
		<%= render 'admin/common/menu' %>
			<div class="col-xs-12 col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 article">
	<!-- 頁面標題 -->
	<div class="page-title"> 
		<h2>新增文章</h2>
	</div>
	<%= bootstrap_form_for [:admin, @post] do |n| %>
	<div class="page-content-wrap">
		<div class="row">
			<div class="col-md-12">
				<!-- 左邊大區塊 -->
				<div class="col-md-8 add-post-left">
					<%= n.text_field :title, class: "form-control", placeholder: "文章名稱" %>	
					<%= n.hidden_field :author, class: "form-control", value: current_user.name %>		
					<%= n.text_area :content, :class => "redactor", :rows => 40, :cols => 120 %>
				</div>
				<!-- 右邊小區塊 -->
				<div class="col-md-4 add-post-right">
					<!-- 發布 -->
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">發佈</h3>
						</div>
						<div class="panel-body">
							<div class="btn-group">								
								<%= link_to('取消', admin_posts_url, class: :"btn btn-default") %>
								<%= n.submit '發佈', class: :"btn btn-primary" %>							
							</div>							
							<div class="pub-section">
								<span class="title">狀態</span>
								<label class="radio-inline">
								<%= n.radio_button :status, "1", label: :"公開", :checked => (@post.status? == true) %>
								</label>
								<label class="radio-inline">
								<%= n.radio_button :status, "0", label: :"隱藏", :checked => (@post.status? == false)%>
								</label>				
							</div>
							<div class="pub-section">
								<span class="title">存成草稿</span>
								<label class="radio-inline">
								<%= n.radio_button :draft, "1", label: :"是", :checked => (@post.status? == true) %>
								</label>
								<label class="radio-inline">
								<%= n.radio_button :draft, "0", label: :"否", :checked => (@post.status? == false)%>
								</label>				
							</div>
						</div>
					</div><!-- 發布 結束-->
					<!-- 分類 -->
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">分類</h3>
						</div>
						<div class="panel-body">
							<div class="checkbox">								
								<%= n.collection_check_boxes :category, PostCategory.all, :id, :name %>
							<a type="button" class="btn btn-default pull-right">增加新類別</a>
						</div>
					</div><!-- 分類 結束-->
					<!-- 標籤 -->
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">標籤</h3>
						</div>
						<div class="panel-body">
							<div class="checkbox">
								<label>
									<%= n.text_field :tag_list, class: "form-control", placeholder: "標籤" %>
									請用逗號做區隔(例:文章,日誌,...)
								</label>
							</div>
						</div>
					</div><!-- 標籤 結束-->
					<!-- 特色圖片 -->
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">特色圖片</h3>
						</div>
						<div class="panel-body">
							<div class="form-group file">
								<input type="file" id="exampleInputFile">
							</div>
						</div>
					</div><!-- 特色圖片 結束-->
				</div><!-- 右邊小區塊 結束 -->
			</div><!-- col-md-12 END -->
		</div><!-- row-fluid END -->
	</div><!-- page-content-wrap END -->
	<% end %>
</div>
</div> <!-- row END -->
</div> <!-- container-fluid END -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevCart</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="../assets/style.css">
  <link rel="stylesheet" type="text/css" href="../../assets/style.css">
  <link rel="stylesheet" type="text/css" href="../../../assets/style.css">
  <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'josephlin'; // required: replace example with your forum shortname

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

  <!-- 選單內收縮 -->
  <script type="text/javascript">
    $(document).ready(function() {
        $(".menu-big-category").click(function() {
            $(".menu-child-category").slideToggle();
        });
    });
  </script>

  <!-- 手機板選單 -->
  <script type="text/javascript">
    $(document).ready(function() {
        $("#toggle-menu").click(function() {
            $(this).toggleClass("active");
            $(".left-side ul").slideToggle();
        });
        //$(".nav > ul > li:has(ul) > a").append('<div class="arrow-bottom"></div>');
        //若有第二層選單則顯示指示箭頭
    });
  </script>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<%= render 'admin/common/head' %>

<div class="blog-container">
	<div class="row">
  	<div class="col-xs-2">
 	  </div>
  <div class="col-xs-10">
		<div class="portfolio-box">
			<% @post_find_status.each do |i| %>
				<div class="blog-post">
					<div class="postblog-content">
						<div class="blog-content">
							<h2>title:<%= link_to i.title, post_path(i) %></h2>
							<b><p>內容:<%= raw i.content %></p></b>
							<p>comments:<%=  %></p>
							<p>views:<%= %></p>
							<p>create_date:<%= i.created_at %></p>					
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	</div>			
</div>

app/views/posts/show.html.erb
<%= render 'admin/common/head' %>

<div class="blog-container">
	<div class="row">
  	<div class="col-xs-2">
 	</div>
  <div class="col-xs-7">
		<div class="portfolio-box">
				<div class="blog-post">
					<div class="postblog-content">
						<div class="blog-content">
							<h2>title:<%= @post.title %></h2>
							<b><p>內容:<%= raw @post.content %></p></b>
							<p>comments:<%=  %></p>
							<p>views:<%= %></p>
							<p>create_date:<%= @post.created_at %></p>
								<div id ="disqus_thread">  
									<%= raw disqus_thread %>  
								</div>  
							<p><%= link_to('返回上層', posts_url) %></p>					
						</div>
					</div>
				</div>
		</div>
	</div>
		<div class="row">
  		<div class="col-xs-3">
 		</div>
	</div>			
</div>